export const mockCandidateData = {
  candidates: [
    {
      id: "cand_1",
      name: "Sarah Johnson",
      email: "sarah.johnson@email.com",
      title: "Senior Full Stack Developer",
      experience: 6,
      location: "San Francisco, CA",
      skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS", "Docker"],
      reputation: 4.8,
      bio: "Passionate about building scalable web applications with modern tech stack. 6+ years of experience in full-stack development.",
    },
  ],
  documents: [
    {
      id: "doc_1",
      name: "Resume_2024.pdf",
      type: "Resume",
      uploadedDate: "2024-01-15",
      verified: true,
      ipfsCid: "QmXxxx1234567890abcdef",
      size: "2.4 MB",
    },
    {
      id: "doc_2",
      name: "AWS_Solutions_Architect_Certification.pdf",
      type: "Certification",
      uploadedDate: "2024-01-10",
      verified: true,
      ipfsCid: "QmYyyy1234567890abcdef",
      size: "1.8 MB",
    },
    {
      id: "doc_3",
      name: "Portfolio_Projects.pdf",
      type: "Portfolio",
      uploadedDate: "2024-01-05",
      verified: true,
      ipfsCid: "QmZzzz1234567890abcdef",
      size: "8.2 MB",
    },
  ],
  interviews: [
    {
      id: "int_1",
      company: "Google",
      position: "Senior Software Engineer",
      date: "2024-02-15",
      time: "2:00 PM",
      type: "Video Call",
      status: "accepted" as const,
      interviewer: "John Smith",
      meetingLink: "https://meet.google.com/abc-defg-hij",
      feedback: "Great technical knowledge and communication skills. Strong problem-solving abilities.",
      rating: 4.5,
    },
    {
      id: "int_2",
      company: "Microsoft",
      position: "Cloud Architect",
      date: "2024-02-20",
      time: "10:00 AM",
      type: "In-person",
      status: "proposed" as const,
      interviewer: "Jane Doe",
      meetingLink: "Microsoft Office, Seattle",
      feedback: null,
      rating: null,
    },
    {
      id: "int_3",
      company: "Amazon",
      position: "Backend Engineer",
      date: "2024-02-10",
      time: "1:30 PM",
      type: "Video Call",
      status: "completed" as const,
      interviewer: "Michael Chen",
      meetingLink: "https://meet.google.com/xyz-uvwx-yz",
      feedback: "Excellent system design knowledge. Very collaborative approach.",
      rating: 4.7,
    },
  ],
  accessRequests: [
    {
      id: "access_1",
      recruiterName: "Acme Inc.",
      recruiterCompany: "Acme Inc.",
      requestedDate: "2024-02-10",
      documents: ["Resume", "Certifications"],
      status: "pending" as const,
      expiryDate: "2024-03-10",
    },
    {
      id: "access_2",
      recruiterName: "TechCorp",
      recruiterCompany: "TechCorp",
      requestedDate: "2024-02-08",
      documents: ["Resume", "Portfolio"],
      status: "granted" as const,
      expiryDate: "2024-03-08",
    },
    {
      id: "access_3",
      recruiterName: "StartupXYZ",
      recruiterCompany: "StartupXYZ",
      requestedDate: "2024-02-05",
      documents: ["Resume"],
      status: "denied" as const,
      expiryDate: null,
    },
    {
      id: "access_4",
      recruiterName: "CloudServices",
      recruiterCompany: "CloudServices",
      requestedDate: "2024-02-01",
      documents: ["Resume", "Certifications", "Portfolio"],
      status: "granted" as const,
      expiryDate: "2024-03-01",
    },
    {
      id: "access_5",
      recruiterName: "DataSystems",
      recruiterCompany: "DataSystems",
      requestedDate: "2024-01-28",
      documents: ["Resume"],
      status: "pending" as const,
      expiryDate: "2024-02-28",
    },
  ],
}

export const mockRecruiterData = {
  candidates: [
    {
      id: "rec_cand_1",
      name: "Sarah Johnson",
      title: "Senior Full Stack Developer",
      experience: 6,
      location: "San Francisco, CA",
      skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
      reputation: 4.8,
      documentsVerified: 3,
    },
    {
      id: "rec_cand_2",
      name: "Alex Chen",
      title: "DevOps Engineer",
      experience: 5,
      location: "New York, NY",
      skills: ["Kubernetes", "Docker", "AWS", "Terraform", "CI/CD"],
      reputation: 4.6,
      documentsVerified: 2,
    },
    {
      id: "rec_cand_3",
      name: "Emma Wilson",
      title: "Product Manager",
      experience: 7,
      location: "Austin, TX",
      skills: ["Product Strategy", "Analytics", "Leadership", "Roadmapping"],
      reputation: 4.9,
      documentsVerified: 4,
    },
    {
      id: "rec_cand_4",
      name: "Michael Brown",
      title: "Data Scientist",
      experience: 4,
      location: "Boston, MA",
      skills: ["Python", "Machine Learning", "SQL", "TensorFlow", "Data Analysis"],
      reputation: 4.7,
      documentsVerified: 3,
    },
    {
      id: "rec_cand_5",
      name: "Lisa Anderson",
      title: "Frontend Engineer",
      experience: 5,
      location: "Seattle, WA",
      skills: ["React", "Vue.js", "CSS", "JavaScript", "Accessibility"],
      reputation: 4.5,
      documentsVerified: 2,
    },
  ],
  interviews: [
    {
      id: "rec_int_1",
      candidateName: "Sarah Johnson",
      position: "Senior Software Engineer",
      date: "2024-02-15",
      time: "2:00 PM",
      type: "Video Call",
      status: "accepted" as const,
      meetingLink: "https://meet.google.com/abc-defg-hij",
    },
    {
      id: "rec_int_2",
      candidateName: "Alex Chen",
      position: "DevOps Lead",
      date: "2024-02-18",
      time: "11:00 AM",
      type: "In-person",
      status: "proposed" as const,
      meetingLink: "Office Conference Room B",
    },
    {
      id: "rec_int_3",
      candidateName: "Emma Wilson",
      position: "Product Manager",
      date: "2024-02-10",
      time: "3:00 PM",
      type: "Video Call",
      status: "completed" as const,
      meetingLink: "https://meet.google.com/xyz-uvwx-yz",
    },
    {
      id: "rec_int_4",
      candidateName: "Michael Brown",
      position: "Senior Data Scientist",
      date: "2024-02-22",
      time: "9:00 AM",
      type: "Video Call",
      status: "proposed" as const,
      meetingLink: "https://meet.google.com/abc-xyz-123",
    },
  ],
  feedback: [
    {
      id: "fb_1",
      candidateName: "Emma Wilson",
      rating: 5,
      comments: "Excellent product thinking and strategic vision. Strong leadership qualities and clear communication.",
      date: "2024-02-10",
    },
    {
      id: "fb_2",
      candidateName: "Michael Brown",
      rating: 4,
      comments:
        "Good technical skills and strong analytical abilities. Needs more experience with production ML systems.",
      date: "2024-02-08",
    },
    {
      id: "fb_3",
      candidateName: "Sarah Johnson",
      rating: 5,
      comments: "Outstanding technical depth and system design knowledge. Perfect fit for the role.",
      date: "2024-02-15",
    },
  ],
}

export const mockAdminData = {
  platformStats: {
    totalUsers: 1247,
    totalCandidates: 892,
    totalRecruiters: 355,
    totalInterviews: 3421,
    totalDocuments: 5634,
    averageReputation: 4.6,
  },
  userGrowth: [
    { month: "Jan", candidates: 120, recruiters: 45 },
    { month: "Feb", candidates: 280, recruiters: 95 },
    { month: "Mar", candidates: 450, recruiters: 150 },
    { month: "Apr", candidates: 620, recruiters: 210 },
    { month: "May", candidates: 750, recruiters: 280 },
    { month: "Jun", candidates: 892, recruiters: 355 },
  ],
  interviewStatus: [
    { status: "Completed", count: 1850 },
    { status: "Scheduled", count: 890 },
    { status: "Proposed", count: 681 },
  ],
}
